# mysql-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: wordpress
type: Opaque
data:
  root_password: cGFzc3dvcmQ=    # Base64-encoded "password"
  database_password: cGFzc3dvcmQ= # Base64-encoded "password"

