apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  labels:
    app: mysql
type: Opaque
data:
  root_password: "cm9vdHBhc3N3b3Jk"  # base64 encoded root password
  database_password: "cGFzc3dvcmQ="  # base64 encoded database password